# Generated by Django 5.0.7 on 2024-08-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
